schema_version: "1.1"
id: "DATA_55-13-02_Environmental-Test-Reqs_rev1.0.0_20281101"
document:
  type: "DATA"
  title: "DATA 55-13-02 Environmental-Test-Reqs"
  revision: "1.0.0"
  effective_date: "2028-11-01"
effectivity: { msn: "ALL" }
approvals:
  - { authority: "Structures Engineering", status: "Released", date: "2028-10-25" }
integrity:
  checksum: { algorithm: "sha256", value: "30561bda841ca0905a86918f82790d76e3ce71b1095bd60bf1c2b3171a0cce5d" }
