schema_version: "1.1"
id: "GOV_Configuration-Management-Plan"
document:
  type: "GOV"
  title: "Configuration Management Plan"
  revision: "1.2.0"
  effective_date: "2025-10-27"
  subject: "Document control and revision management policy"
  ata_chapter: "00"
  category: "Governance and Standards"
effectivity:
  scope: "Program-Wide"
  aircraft_types:
    - "AMPEL360 BWB"
  applicability:
    - "All Personnel"
    - "Engineering"
    - "Documentation"
    - "Quality Assurance"
    - "Configuration Management"
approvals:
  - authority: "Configuration Management Team"
    status: "Released"
    date: "2025-10-27"
  - authority: "Chief Engineering Office"
    status: "Approved"
    date: "2025-10-27"
integrity:
  checksum:
    algorithm: "sha256"
    value: "c62bea111f6435a99407987779a01311ce2d607ff5e298241f559854311c7d19"
revision_history:
  - version: "1.2.0"
    date: "2025-10-27"
    changes: "Added pre-release versioning guidelines and enhanced traceability section"
    author: "Configuration Management Team"
  - version: "1.1.0"
    date: "2025-10-27"
    changes: "Updated effectivity and applicability definitions"
    author: "Configuration Management Team"
  - version: "1.0.0"
    date: "2025-10-27"
    changes: "Initial release of configuration management plan"
    author: "Configuration Management Team"
references:
  standards:
    - "ISO 9001:2015"
    - "AS9100D"
    - "ATA iSpec 2200"
    - "S1000D"
  related_documents:
    - "DOC_OPT-IN-Framework-Philosophy_rev1.0.0_20280101.md"
    - "STD_Metadata-Schema-Guide_rev1.1.0_20280220.md"
    - "STD_Numbering-And-Naming-Conventions_rev1.1.0_20280220.md"
