name: Infra Standards Guard

on:
  pull_request:
    paths:
      - "OPT-IN_FRAMEWORK/I-INFRASTRUCTURES/ATA_85-FLUID_INTERFACES_AND_SERVICING/**"
      - "OPT-IN_FRAMEWORK/I-INFRASTRUCTURES/ATA_86-ELECTRICAL_AND_DATA_INTERFACES/**"
      - "OPT-IN_FRAMEWORK/I-INFRASTRUCTURES/ATA_87-PHYSICAL_AND_AIRFRAME_INTERFACES/**"
      - "OPT-IN_FRAMEWORK/I-INFRASTRUCTURES/ATA_88-GROUND_OPERATIONS_AUTOMATION/**"
      - "OPT-IN_FRAMEWORK/I-INFRASTRUCTURES/ATA_89-INFRASTRUCTURE_COMPLIANCE_AND_CERTIFICATION/**"
      - "OPT-IN_FRAMEWORK/I-INFRASTRUCTURES/ATA_90-RESERVED/**"
      - "OPT-IN_FRAMEWORK/I-INFRASTRUCTURES/schemas_ata85-90/**"
  push:
    branches:
      - main
    paths:
      - "OPT-IN_FRAMEWORK/I-INFRASTRUCTURES/ATA_85-FLUID_INTERFACES_AND_SERVICING/**"
      - "OPT-IN_FRAMEWORK/I-INFRASTRUCTURES/ATA_86-ELECTRICAL_AND_DATA_INTERFACES/**"
      - "OPT-IN_FRAMEWORK/I-INFRASTRUCTURES/ATA_87-PHYSICAL_AND_AIRFRAME_INTERFACES/**"
      - "OPT-IN_FRAMEWORK/I-INFRASTRUCTURES/ATA_88-GROUND_OPERATIONS_AUTOMATION/**"
      - "OPT-IN_FRAMEWORK/I-INFRASTRUCTURES/ATA_89-INFRASTRUCTURE_COMPLIANCE_AND_CERTIFICATION/**"
      - "OPT-IN_FRAMEWORK/I-INFRASTRUCTURES/ATA_90-RESERVED/**"
      - "OPT-IN_FRAMEWORK/I-INFRASTRUCTURES/schemas_ata85-90/**"

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install Python dependencies
        run: |
          pip install pyyaml jsonschema
          
      - name: Install Node dependencies
        run: |
          npm install -g @redocly/cli
          
      - name: Validate metadata sidecars against schema
        run: |
          echo "Validating metadata sidecars..."
          for dir in "OPT-IN_FRAMEWORK/I-INFRASTRUCTURES/ATA_85-FLUID_INTERFACES_AND_SERVICING" \
                     "OPT-IN_FRAMEWORK/I-INFRASTRUCTURES/ATA_86-ELECTRICAL_AND_DATA_INTERFACES" \
                     "OPT-IN_FRAMEWORK/I-INFRASTRUCTURES/ATA_87-PHYSICAL_AND_AIRFRAME_INTERFACES" \
                     "OPT-IN_FRAMEWORK/I-INFRASTRUCTURES/ATA_88-GROUND_OPERATIONS_AUTOMATION" \
                     "OPT-IN_FRAMEWORK/I-INFRASTRUCTURES/ATA_89-INFRASTRUCTURE_COMPLIANCE_AND_CERTIFICATION" \
                     "OPT-IN_FRAMEWORK/I-INFRASTRUCTURES/ATA_90-RESERVED"; do
            python ci/validate_meta.py \
              --schema "OPT-IN_FRAMEWORK/I-INFRASTRUCTURES/schemas_ata85-90/meta_v1_1.json" \
              "$dir"
          done
        continue-on-error: true
        
      - name: Lint OpenAPI specs
        run: |
          echo "Linting OpenAPI specifications..."
          for dir in "OPT-IN_FRAMEWORK/I-INFRASTRUCTURES/ATA_85-FLUID_INTERFACES_AND_SERVICING" \
                     "OPT-IN_FRAMEWORK/I-INFRASTRUCTURES/ATA_86-ELECTRICAL_AND_DATA_INTERFACES" \
                     "OPT-IN_FRAMEWORK/I-INFRASTRUCTURES/ATA_87-PHYSICAL_AND_AIRFRAME_INTERFACES" \
                     "OPT-IN_FRAMEWORK/I-INFRASTRUCTURES/ATA_88-GROUND_OPERATIONS_AUTOMATION" \
                     "OPT-IN_FRAMEWORK/I-INFRASTRUCTURES/ATA_89-INFRASTRUCTURE_COMPLIANCE_AND_CERTIFICATION" \
                     "OPT-IN_FRAMEWORK/I-INFRASTRUCTURES/ATA_90-RESERVED"; do
            find "$dir" \
              -name "API_STD-*.yml" \
              -exec npx @redocly/cli lint {} \;
          done
        continue-on-error: true
        
      - name: Verify digital signatures
        run: |
          echo "Verifying digital signatures..."
          for dir in "OPT-IN_FRAMEWORK/I-INFRASTRUCTURES/ATA_85-FLUID_INTERFACES_AND_SERVICING" \
                     "OPT-IN_FRAMEWORK/I-INFRASTRUCTURES/ATA_86-ELECTRICAL_AND_DATA_INTERFACES" \
                     "OPT-IN_FRAMEWORK/I-INFRASTRUCTURES/ATA_87-PHYSICAL_AND_AIRFRAME_INTERFACES" \
                     "OPT-IN_FRAMEWORK/I-INFRASTRUCTURES/ATA_88-GROUND_OPERATIONS_AUTOMATION" \
                     "OPT-IN_FRAMEWORK/I-INFRASTRUCTURES/ATA_89-INFRASTRUCTURE_COMPLIANCE_AND_CERTIFICATION" \
                     "OPT-IN_FRAMEWORK/I-INFRASTRUCTURES/ATA_90-RESERVED"; do
            python ci/verify_sigs.py "$dir"
          done
        continue-on-error: true
        
      - name: Check for broken links
        run: |
          echo "Checking for broken links and compliance chain..."
          # This would run a link checker script
          echo "⚠ Link checking not yet implemented"
        continue-on-error: true
        
      - name: Summary
        run: |
          echo "::notice::Infrastructure standards validation complete"
          echo "Review any warnings above for compliance issues"
